# Generated by Django 2.1.1 on 2019-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('designition', models.CharField(max_length=40)),
                ('contact', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
                ('salery', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
