# Generated by Django 2.1.1 on 2019-02-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=False, upload_to='my_images'),
        ),
    ]
